export const HomeLabel = {
  CompanyName: {
    id: "id concept",
    en: "id concept",
  },
  CompanyDescription: {
    en: "Transforming Spaces into Sanctuaries of Sound and Style",
    id: "Transforming Spaces into Sanctuaries of Sound and Style",
  },
  CompanyIdentity: {
    title: {
      en: "Who are we?",
      id: "",
    },
    Paragraphs: [
      {
        description: {
          en: "At ID Concept, we specialize in the creation of acoustically refined, serene environments that exude both luxury and tranquility. From private sanctuaries to elite corporate spaces, our expertise in Acoustic Interior Design transforms every room into a sanctuary of unparalleled serenity. We meticulously curate environments free from disruptive Electromagnetic Noise, cultivating a healthier, more balanced atmosphere for optimal well-being.",
          id: "",
        },
      },
      {
        description: {
          en: "Our tailored solutions are designed to deliver superior acoustics and seamless audio-visual integration, including home theaters, music studios, boardrooms, and more. Each space we design is a masterpiece of craftsmanship, offering exceptional acoustics, immersive visuals, and enduring elegance. With years of expertise and a commitment to perfection, we bring your vision to life with unmatched precision, style, and sophistication.",
          id: "",
        },
      },
    ],
  },
  History: {
    title: {
      en: "History",
      id: "Sejarah Perusahaan",
    },
    Paragraphs: [
      {
        description: {
          en: "Our story begins with a deep passion, a lifelong interest, and a fascination with precision-engineered audio systems that has been with us since childhood. Over time, we discovered a fundamental truth: no matter how advanced the sound system, it cannot reach its true potential without the perfect acoustic environment.",
          id: "",
        },
      },
      {
        description: {
          en: "As we delved deeper into this field, we realized that the need for exceptional acoustics goes far beyond just sound systems. There is a growing demand for spaces that provide serenity—environments free from noise and distractions, offering a sense of peace. Whether it's a bedroom, living room, meeting room, office, or any other space, the aspiration to establish personalized sanctuaries of calm and clarity became central to our vision.",
          id: "",
        },
      },
      {
        description: {
          en: "This understanding inspired us to continually expand our knowledge, pursue deep research, and redefine acoustic potential. We focused not only on mastering the technical aspects of acoustics but also on optimizing spaces to foster a sense of well-being and balance. Our mission became clear: to design environments that elevate both sound quality and the overall experience within a space.",
          id: "",
        },
      },
      {
        description: {
          en: "What began as a personal passion has evolved into a company that seamlessly blends advanced acoustics with creative, cutting-edge solutions. We are dedicated to delivering high-performance, tailored environments that enhance both mental and physical well-being. With a highly professional approach and a deep expertise in our field, we are committed to providing solutions that are as unique as the spaces they transform.",
          id: "",
        },
      },
    ],
  },
  CompetitiveAdvantages: {
    title: {
      en: "Competitive advantages",
      id: "Kelebihan dari kompetitor",
    },
    Paragraphs: [
      {
        description: {
          en: "What sets us apart is our extensive experience in creating comprehensive acoustic and audio-visual solutions, seamlessly integrating technical expertise with elegant design to craft harmonious environments. As a company driven by innovation, we offer fully integrated services—from consultation and design to construction—ensuring that every project embodies the highest standards of quality, performance, and functionality.",
          id: "",
        },
      },
      {
        description: {
          en: "Moreover, we distinguish ourselves with a unique focus on harmonizing Electromagnetic Noise, an often overlooked but critical aspect of creating healthy spaces. We are committed to delivering environments that not only excel in acoustics and visuals but also support holistic wellness by minimizing the negative impacts of Electromagnetic Noise. This dedication ensures our spaces offer a safer, more balanced experience for all who inhabit them.",
          id: "",
        },
      },
      {
        description: {
          en: "Understanding Electromagnetic Noise, EMR, and Electromagnetic Pollution",
          id: "",
        },
      },
      {
        description: {
          en: "Electromagnetic Noise refers to irregular, high-frequency electromagnetic disturbances typically generated by modern electronic devices such as chargers, power adapters, inverters, and switching power supplies. This type of noise is non-harmonious and fragmented, often disrupting both sensitive electronic systems and the natural bioelectrical balance of the human body.",
          id: "",
        },
      },
      {
        description: {
          en: "Electromagnetic Noise is a subset of the broader spectrum known as Electromagnetic Radiation (EMR) — which includes both natural sources (like sunlight) and man-made sources (such as Wi-Fi, mobile networks, and household electrical wiring).",
          id: "",
        },
      },
      {
        description: {
          en: "When EMR from artificial sources becomes excessive, continuous, and uncontrolled, it contributes to what is called Electromagnetic Pollution. This refers to the presence of disruptive or biologically stressful EMR in our environment. Within this category, Electromagnetic Noise is one of the most intrusive components, due to its erratic and unstructured frequency patterns.",
          id: "",
        },
      },
      {
        description: {
          en: "To put it simply:",
          id: "",
        },
      },
      {
        description: {
          en: "Electromagnetic Noise → is part of Electromagnetic Pollution → which is part of Electromagnetic Radiation (EMR)",
          id: "",
        },
      },
      {
        description: {
          en: "This deeper understanding empowers us to design environments that minimize disruptive electromagnetic influences — supporting healthier living, improved well-being, and greater peace of mind.",
          id: "",
        },
      },
    ],
  },
  Vision: {
    title: {
      en: "Vision",
      id: "Visi",
    },
    description: {
      en: "Our vision is to redefine the way spaces are experienced by seamlessly blending acoustic excellence, cutting-edge audio and video technology, and sophisticated design. We aim to create environments where sound, atmosphere, and tranquility converge, offering immersive, balanced experiences. Through expert consulting, thoughtful design, and precision construction, we set high standards for high-performance spaces that enhance both functionality and well-being.",
      id: "",
    },
  },
  Mission: {
    title: {
      en: "Mission",
      id: "Misi",
    },
    Points: [
      {
        description: {
          en: "At ID Concept, our mission is to provide bespoke, high-performance audio and video solutions that integrate seamlessly with exceptional design. As consultants, designers, and builders, we collaborate closely with our clients throughout every phase of the project—ensuring that each space reflects their unique vision and needs.",
          id: "",
        },
      },
      {
        description: {
          en: "Leveraging our expertise in acoustic engineering and advanced integration, we craft environments that elevate auditory and visual experiences while promoting peace and well-being. Our commitment to excellence results in precision craftsmanship and harmonious spaces that inspire, comfort, and perform at the highest level.",
          id: "",
        },
      },
    ],
  },
};
