import OfficeBackground from "../assets/images/office-background.jpg";

export const AdvantagesSection = () => {
  return (
    <section
      id="advantages"
      className="py-16 md:py-24 lg:py-32 bg-cover bg-center bg-no-repeat relative"
      style={{
        backgroundImage: `url(${OfficeBackground})`,
      }}
    >
      {/* Background overlay */}
      <div className="absolute inset-0 bg-backgroundSecondary/80"></div>

      {/* Content */}
      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl lg:text-5xl font-bold text-white mb-4">
            Competitive <span className="text-accent">Advantages</span>
          </h2>
        </div>

        <div className="max-w-4xl mx-auto text-center">
          <div className="space-y-6 text-lg md:text-xl leading-relaxed">
            <p className="text-textSecondary">
              <span className="text-accent font-medium">Proven Experience:</span> What sets us apart is our extensive experience in designing and delivering fully integrated acoustic and audio-visual environments. We combine technical expertise with refined aesthetics to create spaces that are both functional and inspiring. From consultation and design to construction, our end-to-end approach ensures every project upholds the highest standards of quality, precision, and performance.
            </p>

            <p className="text-textSecondary">
              <span className="text-accent font-medium">Detail-Oriented Excellence:</span> We take pride in our meticulous attention to detail. Every element—acoustic balance, visual clarity, and material selection—is thoughtfully harmonized to achieve not only superior sound and visual performance but also lasting comfort and elegance. Our process reflects a deep respect for both technology and human experience.
            </p>

            <p className="text-textSecondary">
              <span className="text-accent font-medium">Electromagnetic Pollution Awareness:</span> Beyond acoustics, we address an often-overlooked aspect of modern environments: Electromagnetic Pollution, a disruptive subset of man-made Electromagnetic Radiation (EMR). These invisible interferences, generated by everyday electronic devices and infrastructure, can impact both equipment reliability and human well-being. Through thoughtful design and advanced measurement, we mitigate their effects—creating spaces that promote clarity, safety, and holistic wellness. This awareness embodies our commitment to healthier, more balanced environments.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

